name: ${project.plugin.name}
main: ${project.plugin.mainClass}
version: ${project.version}
description: ${project.description}
author: ${project.plugin.author}
website: ${project.url}
api-version: ${spigot.api.version}

depend: [ProdriversCommons,Parkour,InventoryGUIAPI]
softdepend: [BlueMap,floodgate]
database: true

commands:
    paddon:
        description: Base command for ParkourAddonPlugin.

permissions:
    parkouraddon.help:
        description: Allows to get the help message
        default: op

    parkouraddon.reload:
        description: Allows to reload the plugin
        default: op

    parkouraddon.category.add:
        description: Allows to add a category
        default: op

    parkouraddon.category.list:
        description: Allows to list categories
        default: op

    parkouraddon.category.setprevious:
        description: Allows to set a category's previous category
        default: op

    parkouraddon.category.setreqcoursesnbinprevcat:
        description: Allows to set a category's number of parkour to complete in previous category
        default: op

    parkouraddon.category.setparkoinsreward:
        description: Allows to set a category's parkoins reward amount
        default: op

    parkouraddon.category.sethidden:
        description: Allows to hide and unhide a category
        default: op

    parkouraddon.category.setbaselevel:
        description: Allows to set a category's base level, modifying all levels of categories's parkours
        default: op

    parkouraddon.parkour.setcategory:
        description: Allows to set a parkour's category
        default: op

    parkouraddon.parkour.setdisplayname:
        description: Allows to ste a parkour's display name
        default: op

    parkouraddon.parkour.setdescription:
        description: Allows to set a parkour's description
        default: op

    parkouraddon.parkour.setmcversion:
        description: Allows to set a parkour's minimum Minecraft version
        default: op

    parkouraddon.player.setlevel:
        description: Allows to set a player's level
        default: op

    parkouraddon.player.addparkoins:
        description: Allows to add parkoins to a player
        default: op

    parkouraddon.player.deductparkoins:
        description: Allows to deduct parkoins to a player
        default: op